=== hmcts/cpp-context-listing/listing-command/listing-command-api/src/raml/json/schema/listing.command.update-case-defendant-offences.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "modifiedDate": {
      "$ref": "#/definitions/datePattern"
    },
    "updatedOffences": {
      "type": "array",
      "items": {
        "properties": {
          "defendantId": {
            "$ref": "http://justice.gov.uk/json/schemas/core/data-types.json#/definitions/uuid"
          },
          "caseId": {
            "$ref": "http://justice.gov.uk/json/schemas/core/data-types.json#/definitions/uuid"
          },
          "offences": {
            "type": "array",
            "items": {
              "$ref": "http://justice.gov.uk/progression/events/public.progression.offence.json"
            }
          }
        },
        "required": [
          "defendantId",
          "caseId",
          "offences"
        ]
      }
    },
    "deletedOffences": {
      "type": "array",
      "items": {
        "properties": {
          "defendantId": {
            "$ref": "http://justice.gov.uk/json/schemas/core/data-types.json#/definitions/uuid"
          },
          "caseId": {
            "$ref": "http://justice.gov.uk/json/schemas/core/data-types.json#/definitions/uuid"
          },
          "offences": {
            "type": "array",
            "items": {
              "$ref": "http://justice.gov.uk/json/schemas/core/data-types.json#/definitions/uuid"
            }
          }
        },
        "required": [
          "defendantId",
          "caseId",
          "offences"
        ]
      }
    },
    "addedOffences": {
      "type": "array",
      "items": {
        "properties": {
          "defendantId": {
            "$ref": "http://justice.gov.uk/json/schemas/core/data-types.json#/definitions/uuid"
          },
          "caseId": {
            "$ref": "http://justice.gov.uk/json/schemas/core/data-types.json#/definitions/uuid"
          },
          "offences": {
            "type": "array",
            "items": {
              "$ref": "http://justice.gov.uk/progression/events/public.progression.offence.json"
            }
          }
        },
        "required": [
          "defendantId",
          "caseId",
          "offences"
        ]
      }
    }
  },
  "required": [
    "modifiedDate"
  ],
  "definitions": {
    "datePattern": {
      "type": "string",
      "pattern": "^((([\\+-]?\\d{4}(?!\\d{2}\\b))\\-(0[13578]|1[02])\\-(0[1-9]|[12]\\d|3[01]))|(([\\+-]?\\d{4}(?!\\d{2}\\b))\\-(0[13456789]|1[012])\\-(0[1-9]|[12]\\d|30))|(([\\+-]?\\d{4}(?!\\d{2}\\b))\\-02\\-(0[1-9]|1\\d|2[0-8]))|(((1[6-9]|[2-9]\\d)(0[48]|[2468][048]|[13579][26])|((16|[2468][048]|[3579][26])00))\\-02\\-29))$"
    }
  }
}

=== hmcts/cpp-context-listing/listing-command/listing-command-handler/src/raml/json/listing.command.update-case-defendant-offences.json
{
  "modifiedDate": "2018-03-01",
  "updatedOffences": [
    {
      "caseId": "41a6443f-4906-42ce-8ace-a189b7f2f1b9",
      "defendantId": "0dc09439-b798-4125-88b4-612a16f6a3fc",
      "offences": [
        {
          "id": "7e2f843e-d639-40b3-8611-8015f3a18958",
          "offenceCode": "H8189",
          "wording": "on 01/08/2009 at the county public house, unlawfully and maliciously wounded, John Smith",
          "startDate": "2010-08-01",
          "endDate": "2011-08-01",
          "count": 1,
          "convictionDate": "2017-08-01",
          "offenceTitle": "Wounding with intent",
          "offenceLegislation": "Welsh legislation",
          "offenceTitleWelsh": "Wounding with intent in Welsh",
          "offenceLegislationWelsh": "legislation"
        },
        {
          "id": "d5e03eb8-3274-457c-9db3-e67638c0e8b0",
          "offenceCode": "H8189",
          "wording": "on 01/08/2009 at the county public house, unlawfully and maliciously wounded, Fred Smith",
          "startDate": "2010-08-01",
          "endDate": "2011-08-01",
          "count": 1,
          "convictionDate": "2017-08-01",
          "offenceTitle": "Wounding with intent",
          "offenceLegislation": "Welsh legislation",
          "offenceTitleWelsh": "Wounding with intent in Welsh",
          "offenceLegislationWelsh": "legislation"
        }
      ]
    }
  ],
  "deletedOffences": [
    {
      "caseId": "9e7b3014-2e9f-4c14-8f51-b471f64d52cf",
      "defendantId": "6711d373-c416-426c-92f7-3cd37115f70b",
      "offences": [
        "7e2f843e-d639-40b3-8611-8015f3a18958"
      ]
    }
  ],
  "addedOffences": [
    {
      "defendantId": "6711d373-c416-426c-92f7-3cd37115f70b",
      "caseId": "9e7b3014-2e9f-4c14-8f51-b471f64d52cf",
      "offences": [
        {
          "id": "7e2f843e-d639-40b3-8611-8015f3a18958",
          "offenceCode": "H8189",
          "wording": "on 01/08/2009 at the county public house, unlawfully and maliciously wounded, Billy Smith",
          "startDate": "2010-08-01",
          "endDate": "2011-08-01",
          "count": 1,
          "convictionDate": "2017-08-01",
          "offenceTitle": "Wounding with intent",
          "offenceLegislation": "Welsh legislation",
          "offenceTitleWelsh": "Wounding with intent in Welsh",
          "offenceLegislationWelsh": "legislation"
        }
      ]
    },
    {
      "defendantId": "6711d373-c416-426c-92f7-3cd37115f70b",
      "caseId": "9e7b3014-2e9f-4c14-8f51-b471f64d52cf",
      "offences": [
        {
          "id": "7e2f843e-d639-40b3-8611-8015f3a18958",
          "offenceCode": "H8189",
          "wording": "on 01/08/2009 at the county public house, unlawfully and maliciously wounded, Jack Smith",
          "startDate": "2010-08-01",
          "endDate": "2011-08-01",
          "count": 1,
          "convictionDate": "2017-08-01",
          "offenceTitle": "Wounding with intent",
          "offenceLegislation": "Welsh legislation",
          "offenceTitleWelsh": "Wounding with intent in Welsh",
          "offenceLegislationWelsh": "legislation"
        }
      ]
    }
  ]
}
