=== hmcts/cpp-context-listing/listing-event/listing-event-listener/src/yaml/json/schema/listing.event.hearing-counsel-modified.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/listing/event/listing.event.hearing-counsel-modified.json",
  "type": "object",
  "properties": {
    "hearingId": {
      "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/uuid"
    },
    "counselType": {
      "type": "string",
      "enum": [
        "PROSECUTION",
        "DEFENCE"
      ]
    },
    "action": {
      "type": "string",
      "enum": [
        "ADD",
        "UPDATE",
        "REMOVE"
      ]
    },
    "payload": {
      "type": "string"
    }
  },
  "required": [
    "hearingId",
    "counselType",
    "action",
    "payload"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-listing/listing-command/listing-command-handler/src/test/resources/test-data/listing.command.handler.modify-hearing-counsel.json
{
  "counselType": "DEFENCE",
  "action": "ADD",
  "hearingId": "029034d9-0f54-43c5-ba36-e5deadd62474",
  "payload": "{\"id\":\"fab947a3-c50c-4dbb-accf-b2758b1d2d6d\",\"status\":\"QC\",\"title\":\"Mr\",\"firstName\":\"Eric\",\"lastName\":\"Ormsby\",\"prosecutionCases\":[\"0305de0e-eb0e-478f-8ae4-f2c7966961e3\",\"d06f6539-2a7c-4bc8-bca3-A1e5a225471a\"],\"attendanceDays\":[\"2018-07-17\",\"2018-07-18\",\"2018-07-19\",\"2018-07-21\",\"2018-07-22\"]}"
}
